image: Visual Studio 2017
shallow_clone: true


cache:
  - downloads -> appveyor.yml
  - '%LOCALAPPDATA%\pip\Cache'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\cygwin64\\bin;C:\\msys64;%PATH%"
  - python --version
  - pip install pypiwin32
  - set STATIC_DEPS=true & pip install lxml
  - choco install --allow-empty-checksums dmd
  - choco install --allow-empty-checksums ldc
  - choco install --allow-empty-checksums swig
  - choco install --allow-empty-checksums vswhere  



environment:
  matrix:
    - PYTHON: "C:\\Python27"
      BUILD_JOB_NUM: 1

    # - PYTHON: "C:\\Python35"
    #   BUILD_JOB_NUM: 1

    # - PYTHON: "C:\\Python36"
    #   BUILD_JOB_NUM: 1

    # - PYTHON: "C:\\Python27-x64"
    #   BUILD_JOB_NUM: 1

    # - PYTHON: "C:\\Python35-x64"
    #   BUILD_JOB_NUM: 1
      
    # - PYTHON: "C:\\Python36-x64"
    #   BUILD_JOB_NUM: 1

build: off
build_script:
  - cmd: python enumerate_environment.py 
