image: Visual Studio 2019
shallow_clone: true


on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

cache:
  - downloads -> appveyor.yml
  - '%LOCALAPPDATA%\pip\Cache'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  ### WINDOWS ###
  # add python and python user-base to path for pip installs
  - cmd: "C:\\%WINPYTHON%\\python.exe --version"
  - cmd: for /F "tokens=*" %%g in ('C:\\%WINPYTHON%\\python.exe -m site --user-site') do (set PYSITEDIR=%%g)
  # use mingw 32 bit until #3291 is resolved
  - cmd: "set PATH=C:\\%WINPYTHON%;C:\\%WINPYTHON%\\Scripts;C:\\ProgramData\\chocolatey\\bin;C:\\MinGW\\bin;C:\\MinGW\\msys\\1.0\\bin;C:\\cygwin\\bin;%PATH%"
  - cmd: "C:\\%WINPYTHON%\\python.exe -m pip install -U --progress-bar off pip setuptools wheel "
  - cmd: "C:\\%WINPYTHON%\\python.exe -m pip install -U --progress-bar off pypiwin32 coverage codecov"
  - cmd: set STATIC_DEPS=true & C:\\%WINPYTHON%\\python.exe -m pip install -U --progress-bar off lxml
  # install 3rd party tools to test with
  - cmd: choco install --allow-empty-checksums dmd ldc swig vswhere xsltproc winflexbison
  - cmd: set SCONS_CACHE_MSVC_CONFIG=true
  - cmd: set



environment:
  matrix:
    - WINPYTHON: "Python37"
      PYTHON: "3.7"
      PYVER: 37
      BUILD_JOB_NUM: 1
      COVERAGE: 1
      APPVEYOR_RDP_PASSWORD: 81llyB0B##


    # - PYTHON: "C:\\Python27"
    #   BUILD_JOB_NUM: 1


    # - PYTHON: "C:\\Python35"
    #   BUILD_JOB_NUM: 1

    # - PYTHON: "C:\\Python36"
    #   BUILD_JOB_NUM: 1

    # - PYTHON: "C:\\Python27-x64"
    #   BUILD_JOB_NUM: 1

    # - PYTHON: "C:\\Python35-x64"
    #   BUILD_JOB_NUM: 1
      
    # - PYTHON: "C:\\Python36-x64"
    #   BUILD_JOB_NUM: 1

build: off

before_build:
    - ps: dir "C:\Program Files\Git\usr\bin\x*.exe"
    - ps: |
        if (Test-Path "C:\Program Files\Git\usr\bin\xsltproc.EXE" ) {
          Remove-Item  "C:\Program Files\Git\usr\bin\xsltproc.EXE" -ErrorAction Ignore
        }
    - ps: dir "C:\Program Files\Git\usr\bin\x*.exe"


build_script:
  - cmd: python enumerate_environment.py
  - cmd: git --version
  # - cmd: scons

