image: Visual Studio 2017
shallow_clone: true


# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

cache:
  - downloads -> appveyor.yml
  - '%LOCALAPPDATA%\pip\Cache'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\cygwin64\\bin;C:\\msys64;%PATH%"
  - python --version
  - python -m pip install -U pip
  - pip install wheel
  - pip install pypiwin32
  - pip install --index-url https://test.pypi.org/simple/ scons==3.1.0.alpha.20181015
  - set STATIC_DEPS=true & pip install lxml
  - choco install --allow-empty-checksums dmd
  - choco install --allow-empty-checksums ldc
  - choco install --allow-empty-checksums swig
  - choco install --allow-empty-checksums vswhere
  - choco install --allow-empty-checksums xsltproc
  - choco install --force --allow-empty-checksums --upgrade git.install



environment:
  matrix:
    - PYTHON: "C:\\Python27"
      BUILD_JOB_NUM: 1
      # APPVEYOR_RDP_PASSWORD: 81llyB0B##


    # - PYTHON: "C:\\Python35"
    #   BUILD_JOB_NUM: 1

    # - PYTHON: "C:\\Python36"
    #   BUILD_JOB_NUM: 1

    # - PYTHON: "C:\\Python27-x64"
    #   BUILD_JOB_NUM: 1

    # - PYTHON: "C:\\Python35-x64"
    #   BUILD_JOB_NUM: 1
      
    # - PYTHON: "C:\\Python36-x64"
    #   BUILD_JOB_NUM: 1

build: off

before_build:
    - ps: dir "C:\Program Files\Git\usr\bin\x*.exe"
    - ps: |
        if (Test-Path "C:\Program Files\Git\usr\bin\xsltproc.EXE" ) {
          Remove-Item  "C:\Program Files\Git\usr\bin\xsltproc.EXE" -ErrorAction Ignore
        }

build_script:
  - cmd: python enumerate_environment.py
  - cmd: git --version
  # - cmd: scons

